-- Structure creation

CREATE TABLE HHT_ROLES (
	code CHAR(1 CHAR),
	description VARCHAR2(250 CHAR)
);

ALTER TABLE HHT_ROLES ADD PRIMARY KEY(code);


CREATE TABLE HHT_USERS (
	ID BIGINT,
	FIRST_NAME VARCHAR2(250 CHAR),
	LAST_NAME VARCHAR2(250 CHAR),
	EMAIL VARCHAR2(250 CHAR),
	HHT_ROLE CHAR(1 CHAR),
	PASSWORD VARCHAR2(250 CHAR) DEFAULT 'AZERTY';
);

ALTER TABLE HHT_USERS ADD PRIMARY KEY(ID);


INSERT INTO HHT_ROLES(code, description) VALUES('A','Administrateurs');
INSERT INTO HHT_ROLES(code, description) VALUES('M','Membres');
INSERT INTO HHT_ROLES(code, description) VALUES('V','Visiteurs');
